spring:
  application:
    name: Books

  datasource:
    url: jdbc:postgresql://localhost:2313/books_db
    username: book_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  thymeleaf:
    cache: false